name: CI

on:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "⚠️ אין עדיין טסטים, תוסיף בעתיד"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shlomit-sarel:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/shlomit-sarel:latest