apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shlomit-sarel-ingress
spec:
  rules:
    - host: your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shlomit-sarel
                port:
                  number: 80