apiVersion: v1
kind: Service
metadata:
  name: shlomit-sarel
spec:
  selector:
    app: shlomit-sarel
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
  type: {{ .Values.service.type }}