apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shlomit-sarel
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USERNAME/shlomit-sarel'
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true