name: CI

on:
  push:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Install dependencies
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r project
   
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2          

      - name: Docker Build and Curl Testing 
        run: |
          set -e
          ls -la
          docker build -t shlomit-sarel .
          docker run -d -p 5000:5000 shlomit-sarel

           for i in {1..7}; do
             if curl -f http://localhost:5000; then
               echo "✅ Service is available."
               exit 0
             else
               echo "⏳ Service not available, retrying in 10 seconds..."
               sleep 10
             fi
           done

           echo "❌ Service not available after multiple retries."
           exit 1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shlomit-sarel:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/shlomit-sarel:1.0.$BUILD_NUMBER .
          docker push ${{ secrets.DOCKER_USERNAME }}/shlomit-sarel:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/shlomit-sarel:1.0.$BUILD_NUMBER

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Login to Helm OCI registry (DockerHub)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | helm registry login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io

      - name: Package Helm Chart
        run: |
          helm package charts
          ls -la
          helm push shlomit-sarel-0.1.${GITHUB_RUN_NUMBER}.tgz oci://docker.io/moshelederman
